"""Add AI Conversation models

Revision ID: 07920da01a45
Revises: 9221e6c08509
Create Date: 2026-08-05 21:25:23.924028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07920da01a45'
down_revision: Union[str, None] = '9221e6c08509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ai_messages_chat_id_fkey', 'ai_messages', type_='foreignkey')
    op.drop_table('ai_chats')
    op.add_column('ai_messages', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.add_column('ai_messages', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'ai_messages', 'ai_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_messages', type_='foreignkey')
    op.create_foreign_key('ai_messages_chat_id_fkey', 'ai_messages', 'ai_chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_messages', 'conversation_id')
    op.create_table('ai_chats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_chats_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_chats_pkey')
    )
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
