"""Add Leaderboard entries and Badge models

Revision ID: 1c797f163008
Revises: f1491ded4622
Create Date: 2026-08-05 21:54:22.878866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c797f163008'
down_revision: Union[str, None] = 'f1491ded4622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('threshold_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_slug'), 'badges', ['slug'], unique=True)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('coding_score', sa.Float(), nullable=True),
    sa.Column('contribution_score', sa.Float(), nullable=True),
    sa.Column('roadmap_score', sa.Float(), nullable=True),
    sa.Column('portfolio_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_leaderboard_entries_rank'), 'leaderboard_entries', ['rank'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_total_score'), 'leaderboard_entries', ['total_score'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'badge_id', name='uq_profile_badge')
    )
    op.drop_index('ix_user_metrics_developer_score', table_name='user_metrics')
    op.drop_table('user_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('developer_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_metrics_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_metrics_pkey'),
    sa.UniqueConstraint('user_id', name='user_metrics_user_id_key')
    )
    op.create_index('ix_user_metrics_developer_score', 'user_metrics', ['developer_score'], unique=False)
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_leaderboard_entries_total_score'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_rank'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_badges_slug'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
