"""Add UniqueConstraint to portfolio_projects

Revision ID: 49263646659c
Revises: 7fdd74aa2950
Create Date: 2026-08-05 21:11:20.689118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49263646659c'
down_revision: Union[str, None] = '7fdd74aa2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
