"""Add ai_review cache columns to repositories

Revision ID: 56d58f5e2e93
Revises: 96f54d930383
Create Date: 2026-08-05 21:06:55.268369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d58f5e2e93'
down_revision: Union[str, None] = '96f54d930383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
