"""Add Analytics models

Revision ID: 66b4af958a15
Revises: 2a585ad5db8f
Create Date: 2026-08-05 21:33:44.385677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b4af958a15'
down_revision: Union[str, None] = '2a585ad5db8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('resume_downloads', sa.Integer(), nullable=True),
    sa.Column('github_clicks', sa.Integer(), nullable=True),
    sa.Column('country_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hourly_heatmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'summary_date', name='uq_profile_summary_date')
    )
    op.create_index(op.f('ix_analytics_daily_summaries_summary_date'), 'analytics_daily_summaries', ['summary_date'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_timestamp'), 'analytics_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_timestamp'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_analytics_daily_summaries_summary_date'), table_name='analytics_daily_summaries')
    op.drop_table('analytics_daily_summaries')
    # ### end Alembic commands ###
