"""Add Coding Profile models

Revision ID: 9221e6c08509
Revises: a8e12d38ac62
Create Date: 2026-08-05 21:22:22.166617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9221e6c08509'
down_revision: Union[str, None] = 'a8e12d38ac62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_username', sa.String(length=100), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error_message', sa.String(), nullable=True),
    sa.Column('ai_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'platform', name='uq_profile_platform')
    )
    op.create_table('codechef_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coding_profile_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('current_rating', sa.Integer(), nullable=True),
    sa.Column('highest_rating', sa.Integer(), nullable=True),
    sa.Column('stars', sa.String(length=10), nullable=True),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coding_profile_id'], ['coding_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coding_profile_id')
    )
    op.create_table('codeforces_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coding_profile_id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('max_rank', sa.String(length=50), nullable=True),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.Column('submission_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contest_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['coding_profile_id'], ['coding_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coding_profile_id')
    )
    op.create_table('leetcode_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coding_profile_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.Column('easy_solved', sa.Integer(), nullable=True),
    sa.Column('medium_solved', sa.Integer(), nullable=True),
    sa.Column('hard_solved', sa.Integer(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('submission_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['coding_profile_id'], ['coding_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coding_profile_id')
    )
    op.drop_index('ix_platform_stats_history_recorded_at', table_name='platform_stats_history')
    op.drop_table('platform_stats_history')
    op.drop_index('ix_connected_accounts_platform_name', table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='connected_accounts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='connected_accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_connected_accounts_platform_name', 'connected_accounts', ['platform_name'], unique=False)
    op.create_table('platform_stats_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsed_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], name='platform_stats_history_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='platform_stats_history_pkey')
    )
    op.create_index('ix_platform_stats_history_recorded_at', 'platform_stats_history', ['recorded_at'], unique=False)
    op.drop_table('leetcode_stats')
    op.drop_table('codeforces_stats')
    op.drop_table('codechef_stats')
    op.drop_table('coding_profiles')
    # ### end Alembic commands ###
