"""Add Learning Roadmaps models

Revision ID: a8e12d38ac62
Revises: db047bab37a5
Create Date: 2026-08-05 21:18:35.157605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8e12d38ac62'
down_revision: Union[str, None] = 'db047bab37a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_templates_slug'), 'roadmap_templates', ['slug'], unique=True)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_template_id', sa.UUID(), nullable=False),
    sa.Column('milestone_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bookmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_annotation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_completion_days', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_template_id'], ['roadmap_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'roadmap_template_id', name='uq_profile_roadmap_template')
    )
    op.drop_table('roadmap_tasks')
    op.drop_table('roadmap_weeks')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roadmaps_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='roadmaps_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['roadmap_weeks.id'], name='roadmap_tasks_week_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='roadmap_tasks_pkey')
    )
    op.create_table('roadmap_weeks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name='roadmap_weeks_roadmap_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='roadmap_weeks_pkey')
    )
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('ix_roadmap_templates_slug'), table_name='roadmap_templates')
    op.drop_table('roadmap_templates')
    # ### end Alembic commands ###
