"""Add Resume Builder models

Revision ID: db047bab37a5
Revises: 49263646659c
Create Date: 2026-08-05 21:14:58.422930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db047bab37a5'
down_revision: Union[str, None] = '49263646659c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('current_position', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='visibilityenum'), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('follower_id != following_id', name='check_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('github_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=False),
    sa.Column('total_stars', sa.Integer(), nullable=True),
    sa.Column('total_followers', sa.Integer(), nullable=True),
    sa.Column('total_following', sa.Integer(), nullable=True),
    sa.Column('contribution_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_github_accounts_github_username'), 'github_accounts', ['github_username'], unique=False)
    op.create_table('portfolio_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('theme_name', sa.String(length=30), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('font_family', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(), nullable=True),
    sa.Column('section_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_portfolio_configs_slug'), 'portfolio_configs', ['slug'], unique=True)
    op.create_table('profile_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('viewer_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('GITHUB', 'LINKEDIN', 'TWITTER', 'LEETCODE', 'CODECHEF', 'CODEFORCES', 'GEEKSFORGEEKS', 'PORTFOLIO', name='socialplatformenum'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_educations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('viewer_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_account_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('has_readme', sa.Boolean(), nullable=True),
    sa.Column('has_tests', sa.Boolean(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('ai_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['github_account_id'], ['github_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_repo_id'), 'repositories', ['repo_id'], unique=False)
    op.create_table('portfolio_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demo_url', sa.String(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['github_repo_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('portfolio_id', 'github_repo_id', name='uq_portfolio_github_repo')
    )
    op.drop_constraint('resume_versions_resume_id_fkey', 'resume_versions', type_='foreignkey')
    op.drop_table('resumes')
    op.add_column('resume_versions', sa.Column('profile_id', sa.UUID(), nullable=False))
    op.add_column('resume_versions', sa.Column('title', sa.String(length=150), nullable=False))
    op.add_column('resume_versions', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('resume_versions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('resume_versions', sa.Column('template_name', sa.String(length=30), nullable=True))
    op.add_column('resume_versions', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('resume_versions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('uq_profile_active_resume', 'resume_versions', ['profile_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint('uq_profile_version_number', 'resume_versions', ['profile_id', 'version_number'])
    op.create_foreign_key(None, 'resume_versions', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resume_versions', 'resume_id')
    op.drop_column('resume_versions', 'resume_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('resume_versions', sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.create_foreign_key('resume_versions_resume_id_fkey', 'resume_versions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_profile_version_number', 'resume_versions', type_='unique')
    op.drop_index('uq_profile_active_resume', table_name='resume_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_column('resume_versions', 'updated_at')
    op.drop_column('resume_versions', 'content')
    op.drop_column('resume_versions', 'template_name')
    op.drop_column('resume_versions', 'is_active')
    op.drop_column('resume_versions', 'version_number')
    op.drop_column('resume_versions', 'title')
    op.drop_column('resume_versions', 'profile_id')
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resumes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.drop_table('portfolio_projects')
    op.drop_index(op.f('ix_repositories_repo_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('portfolio_views')
    op.drop_table('portfolio_skills')
    op.drop_table('portfolio_experiences')
    op.drop_table('portfolio_educations')
    op.drop_table('portfolio_certifications')
    op.drop_table('portfolio_achievements')
    op.drop_table('social_links')
    op.drop_table('profile_views')
    op.drop_index(op.f('ix_portfolio_configs_slug'), table_name='portfolio_configs')
    op.drop_table('portfolio_configs')
    op.drop_index(op.f('ix_github_accounts_github_username'), table_name='github_accounts')
    op.drop_table('github_accounts')
    op.drop_table('follows')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
